class REF_TRADE_CLOSE_TYPE:
	ORDER_DRIVEN = 'ORDER_DRIVEN'
	QUANTITY_DRIVEN = 'QUANTITY_DRIVEN'

class REF_TRADE_STATE:
	OPEN_PENDING = 'OPEN_PENDING'
	OPEN_FAILED = 'OPEN_FAILED'
	OPENED = 'OPENED'
	CLOSE_PENDING = 'CLOSE_PENDING'
	CLOSE_FAILED = 'CLOSE_FAILED'
	CLOSED = 'CLOSED'

class REF_ORDER_SIDE:
	BUY = 'BUY'
	SELL = 'SELL'

class REF_ORDER_TYPE:
	MARKET = 'MARKET'
	LIMIT = 'LIMIT'
	STOP_LOSS_LIMIT = 'STOP_LOSS_LIMIT'
	STOP_LOSS_MARKET = 'STOP_LOSS_MARKET'
	TAKE_PROFIT_LIMIT = 'TAKE_PROFIT_LIMIT'
	TAKE_PROFIT_MARKET = 'TAKE_PROFIT_MARKET'

class REF_ORDER_STATE:
	OPEN_PENDING_INT = 'OPEN_PENDING_INT'
	OPEN_PENDING_EXT = 'OPEN_PENDING_EXT'
	OPEN_FAILED = 'OPEN_FAILED'
	OPENED = 'OPENED'
	FILLED = 'FILLED'
	PARTIALLY_FILLED = 'PARTIALLY_FILLED'
	CANCEL_PENDING_INT = 'CANCEL_PENDING_INT'
	CANCEL_PENDING_EXT = 'CANCEL_PENDING_EXT'
	CANCEL_FAILED = 'CANCEL_FAILED'
	CANCELLED = 'CANCELLED'
	REJECTED = 'REJECTED'
	EXPIRED = 'EXPIRED'

class REF_EXEC_TYPE:
	BACKTEST = 'BACKTEST'
	REALTIMETEST = 'REALTIMETEST'

class REF_EXEC_STATE:
	STARTED = 'STARTED',
	FINISHED = 'FINISHED'

class REF_TRADE_TYPE:
	LONG = 'LONG'
	SHORT = 'SHORT'

class REF_INTERVAL:
	INTERVAL_1MINUTE = "1MINUTE"
	INTERVAL_3MINUTE = "3MINUTE"
	INTERVAL_5MINUTE = "5MINUTE"
	INTERVAL_15MINUTE = "15MINUTE"
	INTERVAL_30MINUTE = "30MINUTE"
	INTERVAL_1HOUR = "1HOUR"
	INTERVAL_2HOUR = "2HOUR"
	INTERVAL_4HOUR = "4HOUR"
	INTERVAL_6HOUR = "6HOUR"
	INTERVAL_8HOUR = "8HOUR"
	INTERVAL_12HOUR = "12HOUR"
	INTERVAL_1DAY = "1DAY"
	INTERVAL_3DAY = "3DAY"
	INTERVAL_1WEEK = "1WEEK"
	INTERVAL_1MONTH = "1MONTH"