# INPUT PARAMETERS CONSTANTS
PARAM_MODE_BACKTEST = 'backtest'
PARAM_MODE_TRADING = "trading"
PARAM_MODE_REALTIMETEST = "realtimetest"
PARAM_EXCHANGE_BINANCE = 'binance'
PARAM_EXCHANGE_FILE = 'file'
PARAM_EXCHANGE_DB = 'db'

DEFAULT_CLIENT_SETTINGS_PATH = "./common/client_settings.json"

BACKTEST_TMSTMP_FORMAT = "%Y%m%d%H%M%S"

CRETEN_APP_ROOT_DIR_ENV_VAR = "CRETEN_APP_ROOT_DIR"